name: event_management_app
description: A comprehensive event management platform for college clubs

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Authentication & Security
  flutter_secure_storage: ^9.0.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.2

  # Date & Time
  intl: ^0.19.0

  # Image Handling
  image_picker: ^1.1.2

  # Payment (Razorpay)
  razorpay_flutter: ^1.4.0

  # Calendar Integration
  add_2_calendar: ^3.0.1

  # Notifications
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1

  # Utility
  uuid: ^4.2.1
  url_launcher: ^6.3.1
  share_plus: ^11.0.0

  # File handling
  file_picker: ^8.1.6
  open_file: ^3.5.9

  # Loading and animations
  flutter_spinkit: ^5.2.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
