// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ku3KOiOqb5mvNCPcJzhQhaTcDCCN3KU',
    appId: '1:947941851976:web:your-web-app-id',
    messagingSenderId: '947941851976',
    projectId: 'event-management-app-7797d',
    authDomain: 'event-management-app-7797d.firebaseapp.com',
    storageBucket: 'event-management-app-7797d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ku3KOiOqb5mvNCPcJzhQhaTcDCCN3KU',
    appId: '1:947941851976:android:7086cf4231619d674fe97d',
    messagingSenderId: '947941851976',
    projectId: 'event-management-app-7797d',
    storageBucket: 'event-management-app-7797d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ku3KOiOqb5mvNCPcJzhQhaTcDCCN3KU',
    appId: '1:947941851976:ios:your-ios-app-id',
    messagingSenderId: '947941851976',
    projectId: 'event-management-app-7797d',
    storageBucket: 'event-management-app-7797d.firebasestorage.app',
    iosBundleId: 'com.abhyuday.eventManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ku3KOiOqb5mvNCPcJzhQhaTcDCCN3KU',
    appId: '1:947941851976:ios:your-ios-app-id',
    messagingSenderId: '947941851976',
    projectId: 'event-management-app-7797d',
    storageBucket: 'event-management-app-7797d.firebasestorage.app',
    iosBundleId: 'com.abhyuday.eventManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ku3KOiOqb5mvNCPcJzhQhaTcDCCN3KU',
    appId: '1:947941851976:web:your-web-app-id',
    messagingSenderId: '947941851976',
    projectId: 'event-management-app-7797d',
    authDomain: 'event-management-app-7797d.firebaseapp.com',
    storageBucket: 'event-management-app-7797d.firebasestorage.app',
  );
}
